version: "3.0"

services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - CLIENT_ADDR=${CLIENT_ADDR}
      - API_ADDR=${API_ADDR}
    ports:
      - 8080:8080
  client: 
    depends_on:
      - api
    build: 
      context: ./client
      dockerfile: Dockerfile
    environment:
      - REACT_APP_CLIENT_ADDR=${CLIENT_ADDR}
      - REACT_APP_API_ADDR=${API_ADDR}
    ports:
      - 9001:3000
    restart: unless-stopped
